# Generated by Django 3.1.4 on 2020-12-19 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resturant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('tole', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('cover_photo', models.ImageField(upload_to=resturant.models.get_cover_image_filename)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resturant.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to=resturant.models.get_menu_image_filename)),
                ('price', models.IntegerField()),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.itemtype')),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.resturant')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=resturant.models.get_resturant_image_filename, verbose_name='Image')),
                ('resturant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='resturant.resturant')),
            ],
        ),
    ]
