# Generated by Django 3.1.4 on 2020-12-21 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resturant',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='resturant.contact'),
        ),
        migrations.AlterField(
            model_name='review',
            name='resturant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resturant.resturant'),
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
