# Generated by Django 3.1.4 on 2020-12-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0002_auto_20201221_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
