# Generated by Django 3.1.4 on 2020-12-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0003_contact_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(blank=True, max_length=100)),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='resturant.resturant')),
            ],
        ),
    ]
